### ISSUE TITLE
*-sys crate design

### ISSUE THREAD

**Issue by termoshtt** [rust-cuda/cuda-sys#9]
FFI crate separation, e.g. cuda-sys, cudart-sys, and cublas-sys has benefit

- to separately link to libcuda.so, libcudart.so, libcublas.so
- to better support cargo feature gates disccused in https://github.com/rust-cuda/cuda-sys/pull/5

How to split?
----------------
- cuda-sys
  - FFI for CUDA Driver API (libcuda.so)
- cudart-sys
  - FFI for CUDA Runtime API (libcudart.so)
- cublas-sys
  - FFI for cuBLAS

and so on. (edit: Drop cuFFT)

How to manage?
------------------
- each *-sys crates are managed as a subdirectory in this repository 

```
cuda-sys/cuda-sys/Cargo.toml
         cudart-sys/Cargo.toml
         cublas-sys/Cargo.toml
```

**Comment by LutzCle** [comment]
Would it make sense to reject #4 and open separate PRs for each submodule? Then we could at least get cuda-sys and cudart-sys merged quickly and follow up with the rest. As @kngwyu noted in #4, it's easy to miss some parts that then hold up the entire PR.

**Comment by termoshtt** [comment]
> Would it make sense to reject #4 and open separate PRs for each submodule?

Yes, I'm considering to split code generation part from #4 to enable static code generation at https://github.com/rust-cuda/cuda-sys/tree/code_generator branch (I'm going to create PR for it).
It replaces CUDA8-based binding to CUDA10-based binding which I generated on my env. 

Once code generator is splitted, *-sys separation will be straight forward.
